name: Auto-merge
run-name: Auto-merge Dependabot PRs
on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - main
defaults:
  run:
    shell: bash
jobs:
  merge-prs:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Auto-merge PRs
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: ${{ secrets.FETCH_DEPENDABOT_METADATA }}

      - name: Debug Metadata
        run: |
          echo "Dependabot metadata: ${{ toJson(steps.metadata.outputs) }}"

#      - name: Merge Dependabot PRs
#        run: |
#          gh pr review "${GITHUB_HEAD_REF}" --approve
#          gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
