name: Auto cancel
run-name: Auto cancel redundant workflows
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  auto-cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    name: sleep 180 seconds
    steps:
      - run: echo "Concurrency is ${GITHUB_WORKFLOW}-${GITHUB_REF}."
        env:
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_REF: ${{ github.ref }}
      - run: sleep 180

