name: Function
on:
  workflow_dispatch:
jobs:
    run_function:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Function samples
          env:
            CONTAINS_FUNC: ${{ contains('hello', 'ell') }}
            CONTAINS_FUNC_SENSITIVE: ${{ contains('hello', 'ELL') }}
            STARTS_WITH_FUNC: ${{ startsWith('hello', 'he') }}
            STARTS_WITH_SENSITIVE: ${{ startsWith('hello', 'HE') }}
            ENDS_WITH_FUNC: ${{ endsWith('hello', 'lo') }}
            ENDS_WITH_SENSITIVE: ${{ endsWith('hello', 'LO') }}
            CONTAINS_LABEL: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
            FORMAT_FUNC: "${{ format('First: {0}, Second: {1}', 'first-value!', 'second-value!') }}"
            JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }}
            HASH_FUNC: ${{ hashFiles('README.md') }}
          run: |
            echo "HTML_URL: ${{ toJSON(github.event) }}"
            echo "HTML_URL_FILTERED: ${{ toJSON(github.event.*.html_url) }}"
            echo "CONTAINS_FUNC: ${CONTAINS_FUNC}"
            echo "CONTAINS_FUNC_SENSITIVE: ${CONTAINS_FUNC_SENSITIVE}"
            echo "STARTS_WITH_FUNC: ${STARTS_WITH_FUNC}"
            echo "STARTS_WITH_SENSITIVE: ${STARTS_WITH_SENSITIVE}"
            echo "ENDS_WITH_FUNC: ${ENDS_WITH_FUNC}"
            echo "ENDS_WITH_SENSITIVE: ${ENDS_WITH_SENSITIVE}"
            echo "LABELS: ${{ toJSON(github.event.issue.labels) }}"
            echo "LABEL_NAMES: ${{ toJSON(github.event.issue.labels.*.name) }}"
            echo "CONTAINS_LABEL: ${CONTAINS_LABEL}"
            echo "FORMAT_FUNC: ${FORMAT_FUNC}"
            echo "JOIN_FUNC: ${JOIN_FUNC}"
            echo "HASH_FUNC: ${HASH_FUNC}"
