name: Golang CI
run-name: Golang CI Pipeline
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'go/**/*.go'

jobs:
  test-go:
    runs-on: ubuntu-latest
    name: Test go-lang files
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - run: go test go/excellent/*.go


