name: Logging sample
run-name: Show debug logs
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  logging-sample:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Logging sample
    steps:
      - name: Show debug message
        run: echo "::debug::This is a debug message"

      - name: Turn tracing option on
        run: |
          set -x
          date
          hostname

      - name: Group logs
        run: |
          date
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
          date
          echo "::group::Show say hi"
          echo "Hi!"
          echo "::endgroup::"

      - name: Mask a value
        run: |
          echo "The value is ${MASKED_VALUE}."
          echo "::add-mask::${MASKED_VALUE}"
          echo "The value is ${MASKED_VALUE}."
        env:
          MASKED_VALUE: super_secret_value
