name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: "Hello"
        required: true
        description: A cheerful word
      log-level:
        type: choice
        description: Select the log level
        options:
          - debug
          - info
          - warning
          - error

jobs:
  run_manual:
    runs-on: ubuntu-latest
    steps:
      - env:
          BRANCH: manual-trigger
        run: |
          echo "${{ inputs.greeting }}! Your choice is ${{ inputs.log-level }}."
          echo "${BRANCH} is referred from environment variable."
          echi "${{ env.BRANCH }} is also referred from environment variable."
