name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: "Hello"
        required: true
        description: A cheerful word
      log-level:
        type: choice
        description: Select the log level
        options:
          - debug
          - info
          - warning
          - error

jobs:
  run_manual:
    runs-on: ubuntu-latest
    steps:
      - name: Expression samples
        env:
          BRANCH: manual-trigger
          ACTOR: ${{ github.actor }}
          USERNAME: ${{ vars.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LITERAL_NULL: ${{ null }}
          LITERAL_BOOLEAN: ${{ true }}
          LITERAL_NUMBER: ${{ 12345 }}
          LITERAL_STRING: ${{ 'sample string' }} # string with quotes
          LITERAL_OMISSION_STRING: omit expression notation # string without quotes
        run: |
          echo "${{ inputs.greeting }}! Your choice is ${{ inputs.log-level }}."
          echo "${BRANCH} is referred from environment variable."
          echo "${{ env.BRANCH }} is also referred from environment variable."
          echo "This actor is ${ACTOR}."
          echo "The USERNAME is ${USERNAME}."
          echo "The PASSWORD is ${PASSWORD}."
          echo "The PASSWORD is ${PASSWORD:0:1} ${PASSWORD#?}"
          printenv 
