name: Matrix
run-name: Matrix Job Example
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  print-matrix:
    timeout-minutes: 1
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "This job is running on ${{ matrix.os }}"
