name: Release
run-name: Release Workflow
on:
  workflow_dispatch:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Job
    timeout-minutes: 1
    env:
      # github.ref_name
      # branch push: branch name
      # tag push: tag name
      VERSION: ${{ github.ref_name }}
    permissions:
      # リリースノートの作成に必要
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      # RUNNER_TEMPにて空提供される一時ディレクトリを置き場に使う
      - name: Build
        run: |
          go build -ldflags "-X main.version=${VERSION}" \
          -o "${RUNNER_TEMP}/example" go/example/main.go

      - name: Create Release Notes and Upload
        run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
          gh release upload "${VERSION}" "${RUNNER_TEMP}/example"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

