name: Reporting
run-name: Reporting Workflow
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  reporting:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    name: Reporting Job
    steps:
      - name: Annotation Example
        run: |
          echo "::error::This is an error"
          echo "::warning::This is a warning"
          echo "::notice::This is a notice"

#      - name: Summary Example 1
#        run: |
#          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
#          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
#          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"

      - name: Summary Example 2
        run: |
          cat >> "${GITHUB_STEP_SUMMARY}" << EOF
          ## Example Title 1 ðŸ¥‡
          - first line
          - command: $PWD 
          EOF

#          cat >> "${GITHUB_STEP_SUMMARY}" << 'EOF'
#          ## Example Title 2 ðŸ¥ˆ
#          - second line
#          - command: $PWD
#          EOF
#
#          cat >> "${GITHUB_STEP_SUMMARY}" << EOFABC125
#          ## Example Title 3 ðŸ¥‰
#          - third line
#          - command: $PWD
#          EOFABC125
