name: Schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '*/3 * * * *'  # Every 3 minutes

jobs:
  run-scheduled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow runs every 15 minutes."
      - run: date
