name: Share Data Workflow
run-name: Share Data Workflow Run-Name
on:
  workflow_dispatch:

jobs:
  run-share-data:
    runs-on: ubuntu-latest
    name: Run Share Data Action Job 1
    steps:
      - name: Job1 Step 1
        run: echo 'hello'

      - name: output data
        id: output-data
        run: |
          # <key>=<value> format to set output
          echo "result=Hello" >> ${GITHUB_OUTPUT}
          echo "WORLD=World" >> ${GITHUB_ENV}

      - name: use data
        run: |
          echo "This is a GITHUB_OUTPUT data: ${RESULT}"
          echo "This is a GITHUB_ENV data: ${WORLD}"
        env:
          RESULT: ${{ steps.output-data.outputs.result }}



