name: Status Check
on:
  workflow_dispatch:

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello 1'

      - run: echo 'hello 2'
        if: ${{ success() }}

      - run: exixxxt 1

      - run: echo 'hello 3'
        if: ${{ failure() }}

      - run: echo 'hello 4'
        if: ${{ cancelled() }}

      - run: echo 'hello 5'
        if: ${{ always() }}

      - name: Bad Practice Example, never ends
        uses: actions/checkout@v4
        if: ${{ always() }}

      - run: echo 'hello 6'
        if: ${{ success() }}

      - run: echo 'hello 7'
        if: ${{ failure() }}
