name: Use apis
run-name: Use apis sample
on:
  workflow_dispatch:

jobs:
  run-use-apis:
    name: Use apis samples
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: comment on PR
        run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
